from Service_allocation_algorithms.simple_allocation import *
from Service_allocation_algorithms.best_fit_allocation import *
from Service_allocation_algorithms.random_allocation import *
from Service_allocation_algorithms.less_distance_allocation import *
from Service_allocation_algorithms.best_exposure_time import *
from Service_allocation_algorithms.improved_best_exposure_time import *
from Service_allocation_algorithms.improved_best_fit import *